# Makefile generated by Make My File: https://github.com/MathysCogne/Make_My_File-42
# Date of generation: 06-12-2024 17:52:01

#########################################
#	MINITALK							#
#########################################

NAME = mini_talk

SRCDIR = src
OBJDIR = obj
INCDIR = include

#########################################
#	CLIENT								#
#########################################
CLIENT_NAME = client

CLIENT_SRC = client.c ../utils.c

CLIENT_SRCDIR = src/client/
CLIENT_OBJDIR = $(OBJDIR)/client
CLIENT_SRC := $(addprefix $(CLIENT_SRCDIR), $(CLIENT_SRC))
CLIENT_OBJ = $(CLIENT_SRC:$(CLIENT_SRCDIR)%.c=$(CLIENT_OBJDIR)/%.o)

#########################################
#	SERVER								#
#########################################
SERVER_NAME = server

SERVER_SRC = server.c  ../utils.c

SERVER_SRCDIR = src/server/
SERVER_OBJDIR = $(OBJDIR)/server
SERVER_SRC := $(addprefix $(SERVER_SRCDIR), $(SERVER_SRC))
SERVER_OBJ = $(SERVER_SRC:$(SERVER_SRCDIR)%.c=$(SERVER_OBJDIR)/%.o)


# Libft
LIBFT_DIR := libft
LIBFT := $(LIBFT_DIR)/libft.a
LIBFT_INCLUDE := $(LIBFT_DIR)/include
# Libraries and Linker Flags
LDFLAGS =  -L$(LIBFT_DIR)
LIBS =  $(LIBFT)

# Archiver
AR = ar
ARFLAGS = rcs

# Compiler and Flags
CC = cc
CFLAGS = -Wall -Wextra -Werror -I$(INCDIR) -g3 -I$(LIBFT_INCLUDE)

# Compilation mode (silent by default, set VERBOSE=1 to show commands)
VERBOSE ?= 0
ifeq ($(VERBOSE),1)
  V := 
else
  V := @
endif

# Colors
RED     := "\033[1;31m"
GREEN   := "\033[1;32m"
RESET   := "\033[0m"


all: $(OBJDIR) $(LIBFT) $(CLIENT_NAME) $(SERVER_NAME)

$(NAME): all

#########################################
#	CLIENT								#
#########################################

$(CLIENT_NAME): $(CLIENT_OBJ) $(LIBFT)
	$(V)$(CC) $(CFLAGS) $(LDFLAGS) $(CLIENT_OBJ) $(LIBS) -o $(CLIENT_NAME)
	$(V)echo $(GREEN)"[$(CLIENT_NAME)] Executable created ✅"$(RESET)

$(CLIENT_OBJDIR)/%.o: $(CLIENT_SRCDIR)/%.c | $(CLIENT_OBJDIR)
	$(V)mkdir -p $(dir $@)
	$(V)$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

#########################################
#	SERVER								#
#########################################

$(SERVER_NAME): $(SERVER_OBJ) $(LIBFT)
	$(V)$(CC) $(CFLAGS) $(LDFLAGS) $(SERVER_OBJ) $(LIBS) -o $(SERVER_NAME)
	$(V)echo $(GREEN)"[$(SERVER_NAME)] Executable created ✅"$(RESET)

$(SERVER_OBJDIR)/%.o: $(SERVER_SRCDIR)/%.c | $(SERVER_OBJDIR)
	$(V)mkdir -p $(dir $@)
	$(V)$(CC) $(CFLAGS) -MMD -MP -c $< -o $@

#########################################
# Object Directory Rule
$(OBJDIR):
	$(V)mkdir -p $(OBJDIR) || true

$(CLIENT_OBJDIR):
	$(V)mkdir -p $(CLIENT_OBJDIR) || true

$(SERVER_OBJDIR):
	$(V)mkdir -p $(SERVER_OBJDIR) || true

# Dependency Files
CLIENT_DEP = $(CLIENT_OBJ:.o=.d)
SERVER_DEP = $(SERVER_OBJ:.o=.d)

-include $(CLIENT_DEP)
-include $(SERVER_DEP)

# Libft - Branch 'V.mini_talk_07_12_2024' (No Update before push projet)
$(LIBFT):
	$(V)echo '[$(NAME)] Downloading my Libft from github.com...'$(RESET)
	$(V)@git clone --branch V.mini_talk_07_12_2024 https://github.com/MathysCogne/MyLibft_GNL_Printf.git libft > /dev/null 2>&1
	$(V)echo '[$(NAME)] Compiling Libft...'$(RESET)
	$(V)$(MAKE) --silent -C $(LIBFT_DIR)
	$(V)echo '[$(NAME)] Libft build successfully'

# Clean Rules
clean:
	$(V)echo $(RED)'[$(NAME)] Cleaning objects'$(RESET)
	$(V)rm -rf $(OBJDIR)

fclean: clean
	$(V)echo $(RED)'[$(NAME)] Cleaning all files'$(RESET)
	$(V)rm -f $(CLIENT_NAME) $(SERVER_NAME)
	$(V)$(MAKE) --silent -C $(LIBFT_DIR) fclean
	$(V)echo $(RED)'[libft] Remove directory'$(RESET)
	@rm -rf $(LIBFT_DIR)

re: fclean all

# Makefile Reconfiguration 
regen:
	makemyfile

.PHONY: all clean fclean re bonus regen mini_talk server client
.DEFAULT_GOAL := all
